### ISSUE TITLE
DefineDefaultLocale not working

### ISSUE THREAD

**Issue by philipp-serfling** [robisim74/angular-l10n-sample#2]
in `app.module.ts`

lets say you set ` this.locale.AddConfiguration().DefineDefaultLocale('it', 'IT')` instead of ` this.locale.AddConfiguration()DefineDefaultLocale('en', 'US')`
the language does not change. 
`console.log(this.locale.defaultLocale.languageCode) //  --> "en"`

Am i doing something wrong here?

**Comment by philipp-serfling** [comment]
If i afterwards set the locale with 
`this.locale.setDefaultLocale('it', 'IT');` it is working. 
So i guess in the implementation of 
`LocaleConfig.prototype.DefineDefaultLocale` you just need to do same thing as in `LocaleService.prototype.setDefaultLocale`

**Comment by robisim74** [comment]
By default, _angular-l10n_ uses a cookie to store the selected _defaultLocale_: so, when the user starts the app for the first time, `DefineDefaultLocale` method stores the _defaultLocale_.
`setDefaultLocale` is used to change the _defaultLocale_ at runtime, and it stores the choise of the user.
This a common scenario.
If you are doing tests, you can disable the cookie, calling the _DisableStorage_ method in the configuration (remember to clean the browser cache): in this way, every time you start the app, you get the _defaultLocale_ set in the configuration.

To know the APIs of the library, please see the specification: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md

**Comment by philipp-serfling** [comment]
> By default, angular-l10n uses a cookie to store the selected defaultLocale: so, when the user starts the app for the first time, DefineDefaultLocale method stores the defaultLocale.

And i think this is not working!

Because when i checked out your project and try to set "it, IT" instead of "en, US" in 
`app.module.ts line 26` the language was not set to italian.

**Comment by robisim74** [comment]
Remove the cookie from the cache of your browser (at _localhost:8080_), and try again.

**Comment by philipp-serfling** [comment]
alright, i'll try tomorrow. thank you so far!

**Comment by philipp-serfling** [comment]
Alright, you are perfectly correct! I thought i cleared the cookie but apparently i did not.

So shame on me. 
Feel free to close this issue
