### ISSUE TITLE
[need help] Routing for node.js

### ISSUE THREAD

**Issue by JTOne123** [robisim74/angular-l10n-sample#4]
Hello, sorry about that, it really stupid question, but I need your advice
I can not figure out what I should do with node.js, how to configure it...

What I did:

I had this URL - http://localhost:8080/#/home
```
@NgModule({
    imports: [
        RouterModule.forRoot(routes, {
            useHash: false, /////////////////////////// I disabled hash stategy
            preloadingStrategy: PreloadAllModules
        })
    ],
    exports: [RouterModule]
})
```

Right now, I have this URL http://localhost:8080/home

But after I pressed the F5 button I'm getting exceptions
`Cannot GET /home`

I guess, the fix should be very easy, but I can find nothing about routing in the project

**Comment by robisim74** [comment]
Hi @JTOne123,

this is not a stupid question, but it is a known issue: you can find a lot of discussions on StackOverflow.

However, to work locally using _dev-server_, you have to:
- Comment these lines: https://github.com/robisim74/angular-l10n-sample/blob/master/src/index.html#L7-L9, and add `<base href="/">`
- Add to _webpack.config.js_ (`development `enviroment):
```
        devServer: {
            historyApiFallback: true
        }
```
For every other server, you must provide an appropriate configuration. For _nodejs_, see for example this question (but you can easily find other examples): https://stackoverflow.com/questions/34847972/how-to-handle-angular2-route-path-in-nodejs

Greetings

**Comment by JTOne123** [comment]
Thank you!!!, it is exactly what I'm looking for...
Everything is working right now!
