### ISSUE TITLE
"No key" every where

### ISSUE THREAD

**Issue by DrZytoon** [robisim74/angular-l10n-sample#5]
Hello Roberto,

Your sample have an issue where a lot of words do not translate but display "No key" at the first time loading. Do you know what is the issue? I have the same problem in my website.

**Comment by robisim74** [comment]
I don't see this problem:

![image](https://user-images.githubusercontent.com/14012361/35401420-bb6f211a-01f9-11e8-9906-714b85443c80.png)

Can you explain better?

**Comment by DrZytoon** [comment]
Sure, sorry to didn't do it first.
When I F5 the page, the translation is ok and, about 1 second after, every translated words display "No key" 

![image](https://user-images.githubusercontent.com/29164794/35431439-c6de796e-027c-11e8-92a2-b0b1a1b18836.png)

**Comment by robisim74** [comment]
I still do not see this problem: are you running the app at this address: https://robisim74.github.io/angular-l10n-sample/#/home, or a modified local version?

**Comment by DrZytoon** [comment]
I use your website. I cleared cache, cookies and store to be sure there is no old settings which can cause the issue but the problem is still here.
Thank you for the information that it should work. It may be an issue with my browser.

**Comment by robisim74** [comment]
Which browser are you using?

Open the console, and see if you are getting errors. Open also the Network tab, and see if the http requests of json files are getting a 200 after F5.

As I said, I don't see and I never seen that problem.

**Comment by DrZytoon** [comment]
I use Chrome. Everything is ok when I load the json files.

![image](https://user-images.githubusercontent.com/29164794/35432933-fea308c4-0281-11e8-8511-3a10cc58c367.png)

Well, I'll let you know what the problem is when I'll resolve it. Thanks again.

**Comment by robisim74** [comment]
It's weird... but your browser is loading a library that there isn't in the app. My xhrs:

![image](https://user-images.githubusercontent.com/14012361/35433280-2deace90-0283-11e8-9db6-7352bbc2a7a7.png)

What is `cs.js`?

**Comment by DrZytoon** [comment]
Well see. The cs.css file was download by a chrome extension to display tweets differently. 
I don't know why there was a conflict between it and your library but there was. 
I removed it from chrome and everything is perfectly translated, no more "No key" neither to your website or mine.

Thank you very much!

**Comment by robisim74** [comment]
Uhm... interesting: you should do the test with an Angular app without the library: it seems more a conflict with Angular

**Comment by DrZytoon** [comment]
It's definitively a problem for this extension. For no reason, it appears to check every word on the page and it occurs a problem with the keys I use.

Well, the useless extension is uninstalled so it's ok for me but remember that some chrome extension can disturb your library in case someone comes with an issue like this one.

Than you again.
